# Generated by Django 5.1.7 on 2025-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20250313_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок страницы', max_length=200)),
                ('content', models.TextField(help_text='Основной текст страницы')),
                ('image', models.ImageField(blank=True, help_text='Изображение для страницы', null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': "Страница 'О компании'",
                'verbose_name_plural': "Страницы 'О компании'",
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Номер телефона', max_length=20)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('address', models.CharField(help_text='Адрес', max_length=255)),
                ('map_embed', models.TextField(blank=True, help_text='Код для встраивания карты (например, iframe)', null=True)),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
    ]
